export const resList = [
  {
    id: 1,
    name: "Meghana Foods",
    cuisine: "Biryani, North Indian",
    rating: 3.6,
    time: "28 mins",
    distance: "2.1 km",
    price: "₹350 for two",
    image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_1600,h_640,c_fill/RX_THUMBNAIL/IMAGES/VENDOR/2026/6/15/2659b6d3-d172-4ebc-bfc1-87ab2f3d996e_838740.JPG",
  },
  {
    id: 2,
    name: "Burger King",
    cuisine: "Burgers, Fast Food",
    rating: 3.4,  
    time: "22 mins",
    distance: "1.8 km",
    price: "₹250 for two",
    image: "https://picsum.photos/id/292/400/300",
  },
  {
    id: 3,
    name: "Domino's Pizza Food",
    cuisine: "Pizza, Italian",
    rating: 4.3,
    time: "30 mins",
    distance: "3.2 km",
    price: "₹400 for two",
    image: "https://picsum.photos/id/431/400/300",
  },
  {
    id: 4,
    name: "KFC",
    cuisine: "Chicken, Fast Food",
    rating: 4.5,
    time: "25 mins",
    distance: "2.5 km",
    price: "₹500 for two",
    image: "https://picsum.photos/id/488/400/300",
  },
  {
    id: 5,
    name: "Bikanervala",
    cuisine: "North Indian, Sweets",
    rating: 4.2,
    time: "20 mins",
    distance: "1.5 km",
    price: "₹300 for two",
    image: "https://picsum.photos/id/225/400/300",
  },
  {
    id: 6,
    name: "Pizza Hut",
    cuisine: "Pizza, Pasta",
    rating: 4.4,
    time: "27 mins",
    distance: "2.9 km",
    price: "₹450 for two",
    image: "https://picsum.photos/id/835/400/300",
  },
  {
    id: 7,
    name: "Subway",
    cuisine: "Healthy, Sandwich",
    rating: 4.3,
    time: "18 mins",
    distance: "1.3 km",
    price: "₹280 for two",
    image: "https://picsum.photos/id/292/400/300",
  },
  {
    id: 8,
    name: "Haldiram's",
    cuisine: "South Indian, Snacks",
    rating: 4.5,
    time: "24 mins",
    distance: "2.0 km",
    price: "₹320 for two",
    image: "https://picsum.photos/id/102/400/300",
  },
  {
    id: 9,
    name: "McDonald's Food",
    cuisine: "Burger, Beverages",
    rating: 4.4,
    time: "19 mins",
    distance: "1.7 km",
    price: "₹350 for two",
    image: "https://picsum.photos/id/1060/400/300",
  },
  {
    id: 10,
    name: "Barbeque Nation",
    cuisine: "BBQ, Mughlai",
    rating: 4.7,
    time: "35 mins",
    distance: "4.6 km",
    price: "₹1200 for two",
    image: "https://picsum.photos/id/1081/400/300",
  },
  {
    id: 11,
    name: "Wow! Momo",
    cuisine: "Momos, Chinese",
    rating: 3.3,
    time: "21 mins",
    distance: "2.2 km",
    price: "₹250 for two",
    image: "https://picsum.photos/id/674/400/300",
  },
  {
    id: 12,
    name: "Belgian Waffle",
    cuisine: "Desserts, Waffles",
    rating: 4.6,
    time: "16 mins",
    distance: "1.1 km",
    price: "₹300 for two",
    image: "https://picsum.photos/id/312/400/300",
  },
  {
    id: 13,
    name: "Behrouz Biryani",
    cuisine: "Biryani, Mughlai",
    rating: 3.5,
    time: "32 mins",
    distance: "3.8 km",
    price: "₹600 for two",
    image: "https://picsum.photos/id/823/400/300",
  },
  {
    id: 14,
    name: "Chinese Wok",
    cuisine: "Chinese, Asian",
    rating: 4.2,
    time: "26 mins",
    distance: "2.6 km",
    price: "₹380 for two",
    image: "https://picsum.photos/id/429/400/300",
  },
  {
    id: 15,
    name: "La Pino'z Pizza",
    cuisine: "Pizza, Italian",
    rating: 3.4,
    time: "29 mins",
    distance: "3.0 km",
    price: "₹450 for two",
    image: "https://picsum.photos/id/292/400/300",
  },
];